package com.xiaolanhe.agent.model;

public enum IntentType {
    GENERAL_CHAT,
    FACTUAL_LOOKUP,
    FRESHNESS_LOOKUP,
    STRATEGY_GUIDE,
    COMPARISON,
    PERSONALIZED_RECOMMENDATION,
    TOOL_LIKE_REQUEST,
    NEEDS_CLARIFICATION
}
